import type { Metadata } from 'next';
import { Geist, Geist_Mono, Plus_Jakarta_Sans, Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { cn } from '@/lib/utils';

const poppinsFont = Poppins({
	variable: '--font-sans',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400'],
});

export const metadata: Metadata = {
	title: 'CarePluse',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn('bg-dark-300 min-h-screen font-sans antialiased', poppinsFont.variable)}>
				<ThemeProvider attribute='class' defaultTheme='dark'>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
